version: "3.1"

services:
  nginx:
    image: iksadnorth/nginx-reuse:latest
    container_name: nginx_app
    restart: always
    depends_on:
      - was
    ports:
      - 80:80
      - 443:443
    networks:
      - reuse-bridge
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/logs:/var/log/letsencrypt
      - ./certbot/data:/var/www/certbot
      - ./log/nginx:/var/log/nginx

  was:
    image: iksadnorth/was-reuse:latest
    container_name: was
    restart: always
    ports:
      - 8080:8080
    networks:
      - reuse-bridge
    environment:
      - REDIS_HOST=redis_db
      - REDIS_PASSWORD=q1w2e3r4
      - REDIS_PORT=6379
    depends_on:
      - redis
    volumes:
      - ./log/was:/app/log

  redis:
    image: redis:latest
    container_name: redis_db
    restart: always
    ports:
      - 6379:6379
    networks:
      - reuse-bridge
    volumes:
      - ./log/redis:/var/log/redis

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.6.2
    container_name: filebeat
    user: root
    command: filebeat -e -strict.perms=false
    volumes:
      - ./for-filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ./log:/log
    depends_on:
      - was
      - nginx
      - redis

networks:
  reuse-bridge:
    driver: bridge